### ISSUE TITLE
Late Reporting

### ISSUE THREAD

**Issue by Calorion** [WebVeteran/SpamCop-Deputy#2]
The SpamCopNotify script should be modified not to send items over 48 hours old to SpamCop, but instead to just mark them as junk and trash them.

**Comment by WebVeteran** [comment]
SpamCopNotify is made expressly for submitting to SpamCop. My initial thinking was to use Mail's own Spam button if you don't want to submit to SpamCop. But I see the utility in having a singular function to use in any case. I will look into this.

**Comment by WebVeteran** [comment]
This wasn't too difficult. Done: https://github.com/WebVeteran/SpamCop-Deputy/commit/a6646a259947eb236bcdc6d9f962e5816dd89b6c
Thank you for the idea.
