### ISSUE TITLE
No Content

### ISSUE THREAD

**Issue by Calorion** [WebVeteran/SpamCop-Deputy#3]
Why does SpamCop-Deputy omit the actual text of the message? Can't you just append the raw text of the email without parsing it, as it shows up when you View Source of a message?

**Comment by WebVeteran** [comment]
It's Apple Mail that omits the headers when you forward the message. But it will leave in the content, which may contain trackers.
Also the content can be spoofed super easily. But the headers are harder to forge.
Explicitly getting the raw headers and deleting the content solves all three issues.

**Comment by Calorion** [comment]
But why not include both?

**Comment by WebVeteran** [comment]
It's been a really long time and I don't remember the specifics right now, but I do remember it having to be done in this manner.

- It may be because loading the content will also load the trackers, because drafting an email does not have an options to "do not load images".
- Content can be spoofed really easy. I could get your email server blacklisted by including links to it w/in the content. Spamcop looks at the entire message. Imagine the uses for competitors! I could put in a hidden image with SRC=competitor.com just so they get dinged when people report the message as spam.
- It's the routing information in the header that matter. Not the links in the content.

So at the very least, the usefulness of passing along the content is negligible. But it may be harmful to innocent parties.

**Comment by Calorion** [comment]
So here's the raw source of the message I just received from GitHub, gotten by View Source. It includes both the headers and the content, raw:

`Return-path: <bounces+848413-c0f0-calion=mac.com@sgmail.github.com>
Received: from ms11p00im-qufv17083301.mac.com ([17.58.36.72])
 by ms12531.mac.com
 (Oracle Communications Messaging Server 8.0.1.3.20170906 64bit (built Sep  6
 2017)) with ESMTP id <0P5J002IEMCXF2E0@ms12531.mac.com> for calion@mac.com;
 Tue, 13 Mar 2018 19:05:21 +0000 (GMT)
Original-recipient: rfc822;calion@mac.com
Received: from o4.sgmail.github.com (o4.sgmail.github.com [192.254.112.99])
 by ms11p00im-qufv17083301.me.com
 (Oracle Communications Messaging Server 8.0.1.2.20170607 64bit (built Jun  7
 2017)) with ESMTPS id <0P5J00C6KMCVY840@ms11p00im-qufv17083301.me.com> for
 calion@mac.com (ORCPT calion@mac.com); Tue, 13 Mar 2018 19:05:21 +0000 (GMT)
X-Proofpoint-Spam-Details: rule=notspam policy=default score=9 spamscore=9
 clxscore=1103 suspectscore=2 malwarescore=0 phishscore=0 adultscore=0
 bulkscore=0 classifier=spam adjust=0 reason=mlx scancount=1
 engine=8.0.1-1707230000 definitions=main-1803130213
X-Proofpoint-Virus-Version: vendor=fsecure engine=2.50.10432:,,
 definitions=2018-03-13_08:,, signatures=0
Authentication-results: ms11p00im-qufv17063101.me.com; dmarc=pass
 header.from=github.com
Authentication-results: ms11p00im-qufv10074101.me.com; spf=pass
 (ms11p00im-qufv10074101.me.com: domain of
 bounces+848413-c0f0-calion=mac.com@sgmail.github.com designates 192.254.112.99
 as permitted sender)
 smtp.mailfrom="bounces+848413-c0f0-calion=mac.com@sgmail.github.com"
Received-SPF: pass (ms11p00im-qufv10074101.me.com: domain of
 bounces+848413-c0f0-calion=mac.com@sgmail.github.com designates 192.254.112.99
 as permitted sender) receiver=ms11p00im-qufv10074101.me.com;
 client-ip=192.254.112.99; helo=o4.sgmail.github.com;
 envelope-from="bounces+848413-c0f0-calion=mac.com@sgmail.github.com"
Authentication-results: ms11p00im-qufv10092901.me.com;	dkim=pass (1024-bit key)
 header.d=github.com header.i=@github.com header.b=Jfe0HTId
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com;
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe;
	s=s20150108; bh=gKQwlKfB+XNwd7P4CU6cDjOLh88=; b=Jfe0HTIdAYZEGSfm
	O+PR56HtXuXQC6vurlxa5ckiLH1ODZSiW8fw2S+xdpjCKlPG0xlqNd4id+D0OLrZ
	A9AOKdgEQoi1puN+NIfZpqJQ2aynw8gIQ2ygbsJigi0l2jjWrMashvZux+XFSd75
	EhmNVp14zNiURlQQLX/gt2Kytzc=
Received: by filter0157p1iad2.sendgrid.net with SMTP id
 filter0157p1iad2-7312-5AA820EE-32 2018-03-13 19:05:18.937796642 +0000 UTC
Received: from smtp.github.com (out-2.smtp.github.com [192.30.252.193])
	by ismtpd0024p1mdw1.sendgrid.net (SG) with ESMTP id B9F0OhbkSrmTDjKpPiIfhA	for
 <calion@mac.com>; Tue, 13 Mar 2018 19:05:18.902 +0000 (UTC)
Date: Tue, 13 Mar 2018 19:05:18 +0000 (UTC)

**Comment by WebVeteran** [comment]
Why would you report the message as spam if you don't know what it's about?

When you 'View Raw Source' in Mail that will show you the message content as well. That's different than Applescript's "all headers", which does not include the content.

I don't mean to be argumentative. I just don't understand why you'd want to risk adding yourself to more spam lists my including the content (and trackers) in a draft message.

**Comment by Calorion** [comment]
I report, say, twenty emails at a time. Sometimes more. SpamCop Deputy (correctly) deletes them when it sends them to SpamCop. I don't read those emails; I just glance at them sufficiently to determine that they are spam. But when reported, sometimes I need to see the content in order to discover who they should be reported to.

If AppleScript can't access "View Raw Source" or its equivalent, fine. But I figured it could.

**Comment by WebVeteran** [comment]
I put the ability in place, but disabled by default: https://github.com/WebVeteran/SpamCop-Deputy/commit/811432e4b9c3ab7988647c020421e236261bc127
You're welcome to un/comment the two lines in the notify file, to either send just the headers or the entire source.

**Comment by Calorion** [comment]
Cool! Thanks.

**Comment by Calorion** [comment]
Unfortunately, enabling that option results in an error: 

> error: couldn't parse head
> Message body parser requires full, accurate copy of message

as in https://www.spamcop.net/sc?id=z6453804707zb70750b88f31111e26d57c7bfdf26452z

**Comment by WebVeteran** [comment]
I recommended against using full source because it called issues in the past.  I gave you the option as requested anyway, with a warning.  It's causing issues for you now.

**Comment by WebVeteran** [comment]
Hm... set your Mail preference to compose messages in Plain Text.
I think Mail is composing the new message in rich text which loads tons of formatting w/in the copied source. Give that a shot if you're interested.

**Comment by Calorion** [comment]
I'll try it. 

It does say "Message body parser requires full, accurate copy of message," so I wonder if including only the headers isn't going against SpamCop's policies.

**Comment by WebVeteran** [comment]
The problem I am finding is that if a message was sent in plain text, sending to spamcop in plain text causes the error. But if the message was sent in html and I send in plain, that works fine.
Let me know if your testing produces the same issue. If so I can put some smarts into it (only send full source if message was Rich Text).

Replace some code to automate using plain text:
```
-- OPTIONALLY COPY THE SOURCE (NOT RECOMMENEDED)
set messageBody to (source of thisMessage)
			
-- MAKE IT PLAIN TEXT (NOT RECOMMENEDED)
tell application "System Events"
	click menu item "Make Plain Text" of ((process "Mail")'s (menu bar 1)'s (menu bar item "Format")'s (menu 1))
end tell
```

**Comment by Calorion** [comment]
I don't see a difference when I set it to send in plain text. Analyzing the content of a copied-and-pasted message vs. one created by SpamCop Deputy, however, does reveal a difference:

```
Received: from st11p00im-smtpin002.mac.com ([17.172.80.20])
 by ms55025.mac.com (Oracle Communications Messaging Server 8.0.1.2.20170607
```

for the copied-and-pasted source, and 

```
Received: from st11p00im-smtpin002.mac.com ([17.172.80.20])
by ms55025.mac.com (Oracle Communications Messaging Server 8.0.1.2.20170607
``` 
for the Deputy-created version.

The problem is the one mentioned on [SpamCop's error page](https://www.spamcop.net/fom-serve/cache/368.html): the indenting is missing. I'm not sure why `set messageBody to (source of thisMessage)` eliminates the indenting for wrapped lines, but apparently it does.
