### ISSUE TITLE
SpamCop Deputy keeps hanging Mail

### ISSUE THREAD

**Issue by Calorion** [WebVeteran/SpamCop-Deputy#5]
In Mojave, SpamCop Notify hangs Mail every time. I'm selecting a couple hundred spam messages, activating SpamCop Notify, and then I will get multiple messages like this: 
![Screenshot 2019-03-13 21 16 31](https://user-images.githubusercontent.com/3050950/54326796-ba739b80-45d5-11e9-8130-b1291a60cd20.png) and then the beachball will pop up after I click OK on a few of these (or even if I don't, and just wait a bit), and Mail will never do anything again.

**Comment by WebVeteran** [comment]
@Calorion I see you closed the thread. Is this still an issue or did you get things straightened out?

**Comment by Calorion** [comment]
I decided to just delete all those older messages and not worry about it unless it happened again.
