### ISSUE TITLE
Still works?

### ISSUE THREAD

**Issue by mek363** [WebVeteran/SpamCop-Deputy#6]
I see this hasn't been touched for a while. Does anyone know if t still works? I have a MacBook Pro macOS 12.6.3. I have had a SpamCop account for a while. When I use the scripts to submit, I can see the submits in my "Past Reports" but they say "No Reports Filed". I can submit the same exact headers via web and it is parsed and reported properly. Any ideas?

**Comment by Calorion** [comment]
I use it every day, but I'm still on Catalina.

**Comment by mek363** [comment]
Thanks - I found two issues and got it to work.
1. The auto-responses from SpamCop were going into my Spam folder and it looks like the rule didn't get applied, so I had to add them to the whitelist.
2. The instructions for setting up the mail rule should say "https" not "http". I will see if I can submit a fix for that.
